name: CI

on:
  pull_request:
  push:

jobs:
  fetch-s2-versions:
    name: Fetch SingleStore supported versions
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.get_versions.outputs.versions }}
    steps:
      - name: Get supported versions of SingleStore
        id: get_versions
        uses: singlestore-labs/singlestore-supported-versions@main
        with:
          include_rc: true

  ubuntu-tests:
    name: "Test Ubuntu (Framework: ${{ matrix.framework }}, S2: ${{ matrix.singlestore_version }})"
    needs: fetch-s2-versions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        framework:
          - net8.0
          - net10.0
        singlestore_version: ${{ fromJson(needs.fetch-s2-versions.outputs.versions) }}

    services:
      singlestore:
        image: ghcr.io/singlestore-labs/singlestoredb-dev:latest
        env:
          ROOT_PASSWORD: test
        ports:
          - 3306:3306

    env:
      SINGLESTORE_HOST: 127.0.0.1
      SINGLESTORE_PORT: 3306
      SINGLESTORE_ROOT: root
      SINGLESTORE_PASSWORD: test
      SINGLESTORE_DATABASE: testdb

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install .NET SDKs
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            10.0.x

      - name: Run unit tests
        run: dotnet test SingleStore.SemanticKernel.UnitTests/SingleStore.SemanticKernel.UnitTests.csproj --framework ${{ matrix.framework }} --configuration Release

      - name: Run integration tests
        run: dotnet test SingleStore.SemanticKernel.IntegrationTests/SingleStore.SemanticKernel.IntegrationTests.csproj --framework ${{ matrix.framework }} --configuration Release

  windows-tests:
    name: "Test Windows"
    runs-on: windows-latest

#      SINGLESTORE_HOST: 127.0.0.1
#      SINGLESTORE_PORT: 3306
#      SINGLESTORE_ROOT: root
#      SINGLESTORE_PASSWORD: test
#      SINGLESTORE_DATABASE: testdb

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install .NET SDKs
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Run unit tests
        run: dotnet test SingleStore.SemanticKernel.UnitTests/SingleStore.SemanticKernel.UnitTests.csproj --framework net462 --configuration Release
#
#      - name: Run integration tests
#        run: dotnet test SingleStore.SemanticKernel.IntegrationTests/SingleStore.SemanticKernel.IntegrationTests.csproj --framework ${{ matrix.framework }} --configuration Release
